### Send GET request to auth form
GET http://medialine.loc/auth
Content-Type: application/json

### Send POST request to logout action
POST http://medialine.loc/auth/logout
Content-Type: application/x-www-form-urlencoded

### Send GET request to news list
GET http://medialine.loc/news
Content-Type: application/json

### Send GET request to categories list
GET http://medialine.loc/categories
Content-Type: application/json

### Send GET request to category news
GET http://medialine.loc/news/category/34
Content-Type: application/json
